"""Type stub for Config - declares dynamically registered build_* methods for Pylance."""

from typing import Any, Optional
import torch.nn as nn
from torch.utils.data import DataLoader

class Config:
    def __init__(self, config_file: str = 'detail_config/simple_MNIST_training.yaml'): ...
    def _load_config(self) -> Any: ...
    def build_model_with_config(self, pre_defined_model: Optional[nn.Module]) -> Any: ...
    def build_train_loader_with_config(self) -> Any: ...
    def build_optimizer_with_config(self, model: nn.Module) -> Any: ...
    def build_trainer_with_config(
        self, model: Any, train_data_loader: DataLoader, optimizer: Any
    ) -> Any: ...
    def get(self, key: str, fallback: Any = ...) -> Any: ...

class HookBuilder: ...
